[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = ["core/core.lua"]

[[patches]]
[patches.module]
source = 'modules/nativefs.lua'
before = 'main.lua'
name = 'nativefs'
